# Generated by Django 4.1 on 2022-09-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='type_dr',
            field=models.CharField(choices=[('терапевт', 'терапевт'), ('хирург', 'хирург')], max_length=222),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='state_or_private',
            field=models.CharField(choices=[('государственная', 'государственная'), ('частная', 'частная')], max_length=222),
        ),
    ]
